Description of padNaN
Home > chronux_2_00 > spectral_analysis > pointtimes > padNaN.m
padNaN
PURPOSE
Creates a padded data matrix from input structural array of spike times
SYNOPSIS
function data=padNaN(data)
DESCRIPTION
 Creates a padded data matrix from input structural array of spike times
 pads with NaN
 Usage: data=padNaN(data)
 Input:
 data : structural array of spike times
 Output:
 data : data matrix (zero padded)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
countsig Give the program two spike data sets and one
isi Calculate the inter-spike-interval histogram
psth function to plot trial averaged rate smoothed by
SOURCE CODE
function data=padNaN(data)
% Creates a padded data matrix from input structural array of spike times
% pads with NaN
% Usage: data=padNaN(data)
% Input:
% data : structural array of spike times
% Output:
% data : data matrix (zero padded)
NC=length(data);
fnames=fieldnames(data);
for c=1:NC;
   eval(['Nsp(c)=length(data(c).' fnames{1} ');']);
end;
dtmp(1:max(Nsp),1:NC)=NaN;
for c=1:NC;
    eval(['f=data(c).' fnames{1} ';'])
    dtmp(1:Nsp(c),c)=f;
end;
data=dtmp;