function s=sanitize(input,replacements)
%
%

if ~exist('replacements','var')
  replacements = {...
      {'_','-'}...
      {';',''}...
      {', ','-'}...
      {' ','-'}...
      {'(','-'}...
      {')','-'}};
end


s = foldl(@(it,ac)...
                      strrep(ac,it{:}),...
                      input,...
                      replacements);
