function s=sanitize(input,userSupplied,replacements)
%
%

if ~exist('userSupplied','var')
  userSupplied = {};
end

if ~exist('replacements','var') 
  replacements = {...
      {'_','-'}...
      {';',''}...
      {', ','-'}...
      {' ','-'}...
      {'(','-'}...
      {')','-'}};
end

replacements = [replacements userSupplied];

s = foldl(@(it,ac)...
                      strrep(ac,it{:}),...
                      input,...
                      replacements);
