function dsaggclus(ds)
% DSAGGCLUS(DS) launches the agglomerative clustering based cluster picker
%   The unique (or mostly unique) clusterings found in the
%   dstrialclus phase are themselves clustered agglomeratively and then
%   the user is allowed to click through the clustering tree in search
%   of an appropriate clusterings.  This is not yet implemented.

warning('This function is not yet complete.');

ad.ds = ds;
ad.iname = inputname(1);
ad.f = figure;
%% Create buttons

entries = {};
for i=1:ds.nseg
    entries{i} = sprintf('Segment %d: <unchosen>', i);
end

ad.seglist  =   uicontrol(  'Style', 'listbox',...
                            'Units', 'normalized',...
                            'Position', [.75 .70 .25 .30],...
                            'String', entries );

ad.pupb     =   uicontrol(  'Style', 'pushbutton',...
                            'Units', 'normalized',...
                            'Position', [.75 .65 .05 .05],...
                            'String', 'up',...
                            'Enable', 'off' );

ad.pdnb     =   uicontrol(  'Style', 'pushbutton',...
                            'Units', 'normalized',...
                            'Position', [.8 .65 .05 .05],...
                            'String', 'dn',...
                            'Enable', 'off' );

ad.pgtxt    =   uicontrol(  'Style', 'text',...
                            'Units', 'normalized',...
                            'Position', [.85 .65 .05 .05],...
                            'String', '...',...
                            'Enable', 'off' );

cc = get(ad.pgtxt, 'BackgroundColor');
set(ad.f, 'Color', cc);

ad.seltxt   =   uicontrol(  'Style', 'text',...
                            'Units', 'normalized',...
                            'Position', [.75 .6 .15 .05],...
                            'String', 'Selection:' );

ad.indtxt   =   uicontrol(  'Style', 'text',...
                            'Units', 'normalized',...
                            'Position', [.75 .55 .15 .05],...
                            'String', 'indx: ',...
                            'HorizontalAlignment', 'left' );


% cluster the clusters for the first segment

tc = ds.segs(1).tcluss;
ltc = length(tc);
ms = zeros([ltc ltc]);
for i=1:ltc
    for j=1:ltc
        ms(i,j) = (1/classdistp(tc(i).u{1},tc(j).u{1})) - 1;
    end
end


