% this is a list of constants used by the DSEVTPICKER applet.

ADD_TO      = 1;
REMOVE_FROM = 2;
MARK_OUT    = 3;
ADD_CLUS    = 4;
SELECT      = 5;

EVTMODES = {   'Add',...
            'Remove',...
            'Mark Out',...
            'Create',...
            'Select',...
        };

