function dsevtpicker(ds)
% DSEVTPICKER(DS) starts the event picking application for the dataset
%  object.

dsevtconstants;

for i=1:length(ds.segs)
    ds.segs(i).tchosen = relabel(ds.segs(i).tchosen);
end

ad.inname = inputname(1);

ad.f = figure;

ad.raster = subplot(2,1,1);
set(ad.raster,'Position',[0.1300    0.5838    0.65    0.3412]);
ad.model = subplot(2,1,2);
set(ad.model,'Position',[0.1300    0.1100    0.65    0.3412]);

%% Add mode buttons. %%

ad.modes =  uicontrol(  'Style', 'text',...
                        'Units', 'normalized',...
                        'Position', [.8 .95 .1 .05],...
                        'String', 'Modes',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left'...
                     );

ad.addtobutton=uicontrol( 'Style', 'radiobutton',...
                        'Units', 'normalized',...
                        'Position', [.8 .90 .15 .05],...
                        'String', 'Add To (''A'')',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left',...
                        'Callback', @evttogbutcb...
                     );
ad.selectbutton=uicontrol( 'Style', 'radiobutton',...
                        'Units', 'normalized',...
                        'Position', [.8 .85 .2 .05],...
                        'String', 'Select (''S'')',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left',...
                        'Callback', @evttogbutcb...
                     );
ad.createbutton=uicontrol( 'Style', 'radiobutton',...
                        'Units', 'normalized',...
                        'Position', [.8 .80 .15 .05],...                       
                           'String', 'Create (''K'')',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left',...
                        'Callback', @evttogbutcb...
                     );

ad.toghands = [ad.addtobutton, ad.selectbutton, ad.createbutton];

ad.ds = ds;

ad.edit_segnum = uicontrol( 'Style',    'edit',...
                            'Units',    'normalized',...
                            'Position', [.45 .93 .1 .05],...
                            'String',   '1',...
                            'CallBack', @dsevt_segnumcb );

ad.pb_segnumdn = uicontrol( 'Style',    'pushbutton',...
                            'Units',    'normalized',...
                            'Position', [.4 .93 .05 .05],...
                            'String',   '-',...
                            'CallBack', @dsevt_segnumdncb);

ad.pb_segnumup = uicontrol( 'Style',    'pushbutton',...
                            'Units',    'normalized',...
                            'Position', [.55 .93 .05 .05],...
                            'String',   '+',...
                            'CallBack', @dsevt_segnumupcb);

ad.pb_commit =   uicontrol( 'Style',    'pushbutton',...
                            'Units',    'normalized',...
                            'Position', [.45 .0 .1 .05],...
                            'String', 'commit',...
                            'CallBack', @dsevt_commitcb);

ad.edit_sclus=  uicontrol(  'Style',    'edit',...
                            'Units',    'normalized',...
                            'Position', [.015 .7294 .075 .05],...
                            'String',   '1',...
                            'CallBack', @dsevt_scluscb);

ad.pb_sclusup = uicontrol(  'Style',    'pushbutton',...
                            'Units',    'normalized',...
                            'Position', [.017 .7794 .05 .05],...
                            'String',   '+',...
                            'CallBack', @dsevt_sclusupcb );

ad.pb_sclusdn = uicontrol(  'Style',    'pushbutton',...
                            'Units',    'normalized',...
                            'Position', [.017 .6794 .05 .05],...
                            'String',   '-',...
                            'CallBack', @dsevt_sclusdncb );

ad.text_status= uicontrol(  'Style',    'text',...
                            'Units',    'normalized',...
                            'Position', [.8 0 .2 .05],...
                            'String',   EVTMODES{ADD_TO} );



set(ad.f, 'KeyPressFcn', @dsevt_kdfcn );

ad.mode = ADD_TO;
ad.seg = 1;
ad.tclus = 1;
ad.sclus = 1;

ad.selecting = 0;
ad.selectionlines = [];

ad.triallines = dsevt_gettriallines(ds.segs(ad.seg));

ad.cur_event = [];
ad.cur_id = 1;

dsevt_drawaxes(ad);

set(ad.f, 'UserData', ad);

if nargout == 0
    clear ad
end

