function dsmanseg(ds)
% DSMANSEG interactive segment picker
%
% DSMANSEG(DS) opens the interactive segment picker.
% If DS is a variable in the base workspace, changes will be
% applied to DS.  If DS is not a base variable, one will be created
% with the name DS when changes are committed.
%
% There are three modes in the segment picker: ADD adds a segment division,
% MOVE allows you to move all the divisions except those at either end of
% the data, and DELETE allows you to delete a segment division.
%
% The segment picker allows you to automate the selection of 
% segment divisions by adjusting the approximate number of events
% desired per segment, and the priority that the number be correct
% at the expense of cutting in dense areas, possibly splitting an event.

ad.ds = ds;
ad.inname = inputname(1);

ad.f = figure;
ad.rastax = axes;
set(ad.rastax,'Position',[.1 .2 .65 .65]);
rast(ds.dataset,[],[],'fast');

%% Lay down text box %%

%% Add mode buttons. %%

ad.modes =  uicontrol(  'Style', 'text',...
                        'Units', 'normalized',...
                        'Position', [.8 .95 .1 .05],...
                        'String', 'Modes',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left'...
                     );

ad.addbutton=uicontrol( 'Style', 'radiobutton',...
                        'Units', 'normalized',...
                        'Position', [.8 .90 .1 .05],...
                        'String', 'Add',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left',...
						'Callback', @togbutcb...
                     );
ad.delbutton=uicontrol( 'Style', 'radiobutton',...
                        'Units', 'normalized',...
                        'Position', [.8 .85 .2 .05],...
                        'String', 'Delete',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left',...
						'Callback', @togbutcb...
                     );
ad.movbutton=uicontrol( 'Style', 'radiobutton',...
                        'Units', 'normalized',...
                        'Position', [.8 .80 .1 .05],...
                        'String', 'Move',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left',...
						'Callback', @togbutcb...
                     );
      
ad.toghands = [ad.addbutton ad.delbutton ad.movbutton];
                       



ad.status = uicontrol(  'Style', 'text',...
                        'Units', 'normalized',...
                        'Position', [.02 .02 .1 .05],...
                        'String', 'Status...',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left'...
                     );

helpstring = 'For help type ">>help dsmanseg" on the interpreter';
ad.helpbox = uicontrol( 'Style', 'text',...
                        'Units', 'normalized',...
                        'Position', [.12 .95 .6 .05],...
                        'String', helpstring,...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left'...
                      );

ad.pertext = uicontrol( 'Style', 'text',...
                        'Units', 'normalized',...
                        'Position', [.2 .1 .1 .05],...
                        'String', 'per',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left'...)
                      );
try
ad.peredit = uicontrol( 'Style', 'edit',...
                        'Units', 'normalized',...
                        'Position', [.3 .1 .1 .05],...
                        'String', sprintf('%d',ds.per),...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left',...
                        'KeyPressFcn', @zdsms_ekeydn,...
                        'UserData', {'peredit', 1},...
                        'CallBack', @zdsms_edcb...
                      );
catch
ad.peredit = uicontrol( 'Style', 'edit',...
                        'Units', 'normalized',...
                        'Position', [.3 .1 .1 .05],...
                        'String', sprintf('%d',ds.per),...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left',...
                        'UserData', {'peredit', 1},...
                        'CallBack', @zdsms_edcb...
                      );
end                 

ad.partext = uicontrol( 'Style', 'text',...
                        'Units', 'normalized',...
                        'Position', [.2 .05 .1 .05],...
                        'String', 'segpar',...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left'...)
                      );
try
ad.paredit = uicontrol( 'Style', 'edit',...
                        'Units', 'normalized',...
                        'Position', [.3 .05 .1 .05],...
                        'String', sprintf('%f',ds.segparam),...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left',...
                        'KeyPressFcn', @zdsms_ekeydn,...
                        'UserData', {'paredit', 1},...
                        'CallBack', @zdsms_edcb...
                      );
catch
ad.paredit = uicontrol( 'Style', 'edit',...
                        'Units', 'normalized',...
                        'Position', [.3 .05 .1 .05],...
                        'String', sprintf('%f',ds.segparam),...
                        'BackgroundColor', get(ad.f, 'Color'),...
                        'HorizontalAlignment', 'left',...
                        'UserData', {'paredit', 1},...
                        'CallBack', @zdsms_edcb...
                      );
end
ad.commit = uicontrol(  'Style', 'pushbutton',...
                        'Units', 'normalized',...
                        'Position', [.45 .01 .1 .05],...
                        'String', 'Commit Changes',...
                        'BackgroundColor', get(ad.f,'Color'),...
                        'CallBack', @zdsms_commit );

ad.mode = 'a';

set(ad.f, 'KeyPressFcn', @zdsms_fkeydn);
set(ad.rastax,'ButtonDownFcn', @zdsms_fbdf );
                     



set(ad.f, 'UserData', ad);

