Description of fitted
Home > chronux_2_00 > locfit > m > fitted.m
fitted
PURPOSE
Fitted values from a locfit object.
SYNOPSIS
function y = fitted(fit)
DESCRIPTION
 Fitted values from a locfit object.
 Input arguments:
   fit - the locfit() fit.
  Author: Catherine Loader.
CROSS-REFERENCE INFORMATION
This function calls:
backtr
predict Interpolate a fit produced by locfit().
This function is called by:
lf_censor
SOURCE CODE
function y = fitted(fit)
% Fitted values from a locfit object.
%
% Input arguments:
%   fit - the locfit() fit.
%
%  Author: Catherine Loader.
z = predict(fit,'d','restyp','fit');
y = backtr(z,fit);
return;