Description of smooth_lf
Home > chronux_2_00 > locfit > m > smooth_lf.m
smooth_lf
PURPOSE
must (unlike R smooth.lf() function) give x and y.
SYNOPSIS
function z=smooth_lf(x,y,varargin)
DESCRIPTION
 must (unlike R smooth.lf() function) give x and y.
 also R's direct=T is automatic.
CROSS-REFERENCE INFORMATION
This function calls:
invlink inverse link function for locfit.
lfknots
locfit Smoothing noisy data using Local Regression and Likelihood.
This function is called by:
SOURCE CODE
function z=smooth_lf(x,y,varargin)
% must (unlike R smooth.lf() function) give x and y.
% also R's direct=T is automatic.
%
xev = x;
if (k>1)
  if (strcmp(varargin{1},'xev'))
    xev = varargin{2};
    varargin(1:2) = [];
  end;
end;
fit = locfit(x,y,varargin{:},'ev',xev,'module','simple');
z = lfknots(fit);
fv = invlink(z(:,1),fit.fit_points.family_link);
z = { xev, fv };
return;